// src/components/about-me/Bio.vue
<template>
    <section class="me-container">
        <HeaderIcon icon="/assets/img/icons/header-icons/user.svg" alt="me" />

        <p>
            <span itemProp="name">{{bio.name}}</span>
        </p> 

        <p class="rich-snippet-only">
            <span itemProp="jobTitle">{{bio.jobTitle}}</span>
        </p>

        <p v-if="bio.nationality">
          {{ $t("me.nationality") }} {{bio.nationality}}
        </p>

        <p>
            {{ $t("me.birthDate") }}
            <DateDisplay 
                :input-date="bio.birth"
                :output-date-format="$t('date_format')" />
        </p>

        <span itemProp="address">
            <span 
                v-for="(addressLine, i) in addressArray"
                :key="i"
            >
            {{addressLine}}
            <br />
            </span>
        </span>

        <p>
            <a itemProp="email" :href="'mailto:' + bio.email">
            {{bio.email}}
            </a>
        </p>

        <p>
            {{ $t("me.phone") }}
            <span itemProp="telephone">{{bio.phoneNumber}}</span>
        </p>

        <p class="rich-snippet-only">
            <span itemProp="url">{{bio.url}}</span>
        </p>

        <p>
            <a
                itemProp="sameAs"
                :href="'https://twitter.com/' + bio.twitterId"
                target="_blank"
                class="twitter-link"
            >
            twitter.com/RougeMine
            </a>
        </p>

    </section>
</template>

<script lang="ts">
import Vue from "vue";
import { mapState } from "vuex";
import { AppState, ResumeDataBio } from "@/domain";
import DateDisplay from "@/components/misc/DateDisplay.vue";
import HeaderIcon from "@/components/misc/HeaderIcon.vue";

export default Vue.extend({
  components: {
    HeaderIcon,
    DateDisplay,
  },
  computed: {
    ...mapState({
      // Returns the "Bio" data for the current language
      bio: function(state: AppState): ResumeDataBio {
        return state.resume.bio[state.lang];
      },
    }),
    addressArray: function(): string[] {
      const me = this as any; // yeah. sometimes TypeScript makes me do that :-/
      const bio = me.bio as ResumeDataBio;
      return bio.address.split("\n");
    },
  },
});
</script>

// src/components/Me/Bio.tsx
import * as React from "react";
import { LangContext } from "../../contexts/LangContext";
import { I18N_DATA } from "../../data/i18n-data";
import { RESUME_DATA } from "../../data/resume-data";
import { parseISO as parseISODate, format as formatDate } from "date-fns";

export function MeBio(props: {}): React.ReactElement {
  const langCode = React.useContext(LangContext);

  const i18n = I18N_DATA[langCode];
  const bio = RESUME_DATA[langCode].bio;

  const birthDate = parseISODate(bio.birth);
  const dateFormat = i18n.date_format;

  return (
    <section className="me-container">
      {/* <HeaderIcon icon="/assets/img/icons/header-icons/user.svg" alt="me" /> */}

      <p>
        <span itemProp="name">{bio.name}</span>
      </p>

      <p className="sr-only">
        <span itemProp="jobTitle">{bio.jobTitle}</span>
      </p>

      {bio.nationality && (
        <p>
          {i18n.me.nationality} {bio.nationality}
        </p>
      )}

      <p>
        {i18n.me.birthDate}
        {formatDate(birthDate, dateFormat)}
      </p>

      <span itemProp="address">
        {bio.address.split("\n").map((addressLine, i) => {
          return (
            <span key={i}>
              {addressLine}
              <br />
            </span>
          );
        })}
      </span>

      <p>
        <a itemProp="email" href={`mailto:${bio.email}`}>
          {bio.email}
        </a>
      </p>

      <p>
        {i18n.me.phone}
        <span itemProp="telephone">{bio.phoneNumber}</span>
      </p>

      <p className="sr-only">
        <span itemProp="url">{bio.url}</span>
      </p>

      <p>
        <a itemProp="sameAs" href={`https://twitter.com/${bio.twitterId}`} target="_blank" className="twitter-link">
          twitter.com/RougeMine
        </a>
      </p>
    </section>
  );
}
